apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: dagger-runners
  namespace: dagger-runners
spec:
  template:
    metadata:
      labels:
        app: dagger-runners
        node-for: dagger-runners

      # Annotations are arbitrary key-values that are applied to all nodes
      annotations:
        created-by: karpenter
        created-for: dagger-runners

    spec:
      nodeClassRef:
        name: dagger-runners

      taints:
        - key: dagger-runners
          effect: NoSchedule

      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          # NOTE: c6id nodes have NVME disks and fast CPUs. They are very powerful
          # but very expensive.
          values: ["c6id"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          # NOTE: you should customize this to select the instance sizes that you want
          values: ["large", "xlarge"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]

  disruption:
    # NOTE: We want WhenEmpty to prevent exisiting nodes from being terminated in the middle of running
    # a pipeline.
    consolidationPolicy: WhenEmpty
    consolidateAfter: 90s
    expireAfter: 240h


  # TODO: define limits that make sense for your expectations
  limits:
    cpu: "32"
    memory: "64Gi"
